### ISSUE TITLE
Space_Travelers_Hub project task distribution 

### ISSUE THREAD

**Issue by Atifzada** [Atifzada/Space_Travelers-_Hub#25]
#### Group Members
This project would be done by @Atifzada Sololy  Due to Internet Issues resulting in hindering the group project activity. I have removed tasks for the Third Team member but the Second Team member's tasks are still present. Please guide me so that I can remove those tasks and just focus on First Team Member's tasks to complete this project within the timeline.

**Comment by NahnahAJ** [comment]
## Project Status: INVALIDATED :red_circle: 
Hi @Atifzada , 

While you made a great effort in this project, I can't go ahead and review your code.
<img src="https://media2.giphy.com/media/TiUYdWptTqn8yOk1Dp/giphy.gif"/>

## Invalid Code Review Request

- This is because you have submitted a project, that is a `group project` and as a result needs to be collaborated on by both you and your partner or partners.
- However, if for some reason you have to do the project alone, then attach a screenshot of the message you received from student success stating that you can do the project alone 💯 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @NahnahAJ in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Atifzada** [comment]
#### Below are the screenshots of the complete conversation with the student success team:

![image](https://github.com/Atifzada/Space_Travelers-_Hub/assets/116461959/083401c6-12e3-4ff7-a611-d51f81cdcde7)

![image](https://github.com/Atifzada/Space_Travelers-_Hub/assets/116461959/a216c691-cac1-4a0f-801a-09cdad1eafef)

![image](https://github.com/Atifzada/Space_Travelers-_Hub/assets/116461959/34ebae00-350f-40cf-a463-599f8a5ed6cd)

![image](https://github.com/Atifzada/Space_Travelers-_Hub/assets/116461959/d11e45fe-a182-488d-8e2c-fc0c15cb850c)

**Comment by frank1738** [comment]
Hi @Atifzada , 

You can go ahead with your project
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/da75JuW2HHuBNqOHHE/giphy.gif"/>

## Highlights

✅ Tasks are assigned well and are descriptive

## Optional suggestions

N/A
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
